spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?useUnicode=true&serverTimezone=UTC
        user: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        schema: schema.sql
        data: data.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
logging:
    level:
        ROOT: INFO