spring:
    data:
        mongodb:
            database: library
            #authentication-database: admin
            #username: root
            #password: root
            port: 27017
            host: localhost
logging:
    level:
        ROOT: INFO