spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?useUnicode=true&serverTimezone=UTC
        user: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        schema: schema.sql
        data: data.sql