INSERT INTO AUTHORS VALUES(1, 'Alexandre Dumas');
INSERT INTO AUTHORS VALUES(2, 'Ernest Hemingway');
INSERT INTO AUTHORS VALUES(3, 'Samerset Moem');
INSERT INTO AUTHORS VALUES(4, 'Alexander Pushkin');
INSERT INTO AUTHORS VALUES(5, 'Barbara Sher');

INSERT INTO GENRES VALUES(1, 'Drama');
INSERT INTO GENRES VALUES(2, 'Novel');
INSERT INTO GENRES VALUES(3, 'Comedy');
INSERT INTO GENRES VALUES(4, 'Thriller');
INSERT INTO GENRES VALUES(5, 'Psychology');
INSERT INTO GENRES VALUES(6, 'Poetry');

INSERT INTO BOOKS VALUES(1, 'The Three Musketeers', 1);
INSERT INTO BOOKS VALUES(2, 'The Count of Monte Cristo', 1);
INSERT INTO BOOKS VALUES(3, 'The Old Man and the Sea', 2);
INSERT INTO BOOKS VALUES(4, 'Wishcraft', 5);
INSERT INTO BOOKS VALUES(5, 'Ruslan and Ludmila', 4);

INSERT INTO BOOK_GENRE VALUES(1, 2);
INSERT INTO BOOK_GENRE VALUES(1, 3);
INSERT INTO BOOK_GENRE VALUES(2, 1);
INSERT INTO BOOK_GENRE VALUES(2, 2);
INSERT INTO BOOK_GENRE VALUES(3, 1);
INSERT INTO BOOK_GENRE VALUES(4, 5);
INSERT INTO BOOK_GENRE VALUES(5, 6);