INSERT INTO AUTHORS VALUES(1, 'Alexandre Dumas');
INSERT INTO AUTHORS VALUES(2, 'Ernest Hemingway');

INSERT INTO GENRES VALUES(1, 'Drama');
INSERT INTO GENRES VALUES(2, 'Novel');
INSERT INTO GENRES VALUES(3, 'Comedy');
INSERT INTO GENRES VALUES(4, 'Thriller');

INSERT INTO BOOKS VALUES(1, 'The Three Musketeers', 1);
INSERT INTO BOOKS VALUES(2, 'The Count of Monte Cristo', 1);
INSERT INTO BOOKS VALUES(3, 'The Old Man and the Sea', 2);

INSERT INTO BOOKTOGENRE VALUES(1, 1, 2);
INSERT INTO BOOKTOGENRE VALUES(2, 1, 3);
INSERT INTO BOOKTOGENRE VALUES(3, 2, 1);
INSERT INTO BOOKTOGENRE VALUES(4, 2, 2);
INSERT INTO BOOKTOGENRE VALUES(5, 3, 1);