DROP TABLE IF EXISTS books;
CREATE TABLE books(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), authorId INT, PRIMARY KEY(id));

DROP TABLE IF EXISTS authors;
CREATE TABLE authors(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY(id));

DROP TABLE IF EXISTS genres;
CREATE TABLE genres(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY(id));

DROP TABLE IF EXISTS bookToGenre;
CREATE TABLE bookToGenre(id INT NOT NULL AUTO_INCREMENT, bookId INT,  genreId INT, PRIMARY KEY(id));
